# Generated by Django 5.2.1 on 2025-06-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_migrate_to_order_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyuser',
            options={'verbose_name': 'Сотрудник компании', 'verbose_name_plural': 'Сотрудники компании'},
        ),
        migrations.AlterModelOptions(
            name='salarycalculation',
            options={'ordering': ['-period_year', '-period_month'], 'verbose_name': 'Расчёт зарплаты', 'verbose_name_plural': 'Расчёты зарплат'},
        ),
        migrations.RemoveField(
            model_name='salarycalculation',
            name='total_amount',
        ),
    ]
